spring:
  data:
    mongodb:
      username: admin
      password: cognizant
      host: localhost
      port: 27019
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.brihaspathee.ecommerce.web.model.OrderConfirmation, paymentNotificationRequest:com.brihaspathee.ecommerce.web.model.PaymentConfirmation
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: balaji
    password: cognizant
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 7096