spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: cognizant
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 7094
application:
  config:
    customer-url: http://localhost:7092/api/v1/customers
    product-url: http://localhost:7093/api/v1/products
    payment-url: http://localhost:7095/api/v1/payments