services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cognizant
      PGDATA: /var/lib/postgresql/data
networks:
  phoenix-net

volumes:
  postgres:
  pgadmin:
  mongo: